### ISSUE TITLE
Doesn't work with rustc 1.40

### ISSUE THREAD

**Issue by corebreaker** [ProgrammingRust/examples#4]
Hello, for iron-gcd, the crate urlencoded has the version 0.5.0 which is not compatible with rustc 1.40. But iron-gcd can be compiled with the urlencoded crate in the version v0.6.0.

![image](https://user-images.githubusercontent.com/9797898/74353128-c3f31e00-4db9-11ea-8696-77d70ba038e8.png)

**Comment by corebreaker** [comment]
I found that's work with theses dependencies:
```toml
iron = "0.6.1"
mime = "0.2.6"
router = "0.6.0"
urlencoded = "0.6.0"
```

The other files is unchanged.
